export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'

export const LISTA_USUARIOS = 'LISTA_USUARIOS'
export const ADICIONA_USUARIO = 'ADICIONA_USUARIO'
export const ALTERA_USUARIO = 'ALTERA_USUARIO'
export const EXCLUIR_USUARIO = 'EXCLUIR_USUARIO'

export const NOTIFICAR = 'NOTIFICAR'